# Generated by Django 2.0.6 on 2018-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('event_title_thai', models.CharField(max_length=200)),
                ('event_description_thai', models.CharField(max_length=10000)),
                ('event_title_eng', models.CharField(max_length=200)),
                ('event_description_eng', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title_thai', models.CharField(max_length=200)),
                ('place_title_eng', models.CharField(max_length=200)),
                ('place_description_thai', models.CharField(max_length=10000)),
                ('place_description_eng', models.CharField(max_length=10000)),
            ],
        ),
    ]
