# Generated by Django 2.0.6 on 2018-06-04 15:20

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_description_eng',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_description_thai',
        ),
        migrations.AddField(
            model_name='event',
            name='event_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), null=True, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='place_event_list',
            field=models.ManyToManyField(related_name='place_event_list', to='map_site.Event'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), null=True, size=None),
        ),
        migrations.AddField(
            model_name='place',
            name='place_location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description_thai',
            field=models.TextField(),
        ),
    ]
