# Generated by Django 2.0.6 on 2018-06-08 05:57

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0002_auto_20180604_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
