# Generated by Django 2.0.6 on 2018-06-08 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0003_auto_20180608_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='pic_folder/Event/no-img.jpg', upload_to='pic_folder/'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default='pic_folder/Place/no-img.jpg', upload_to='pic_folder/'), null=True, size=None),
        ),
    ]
