# Generated by Django 2.0.6 on 2018-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0004_auto_20180608_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image_path', models.FilePathField()),
                ('image_file', models.ImageField(upload_to=models.FilePathField())),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_images',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_images',
        ),
        migrations.AddField(
            model_name='event',
            name='event_images',
            field=models.ManyToManyField(null=True, related_name='event_image_list', to='map_site.ImageModel'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_images',
            field=models.ManyToManyField(null=True, related_name='place_image_list', to='map_site.ImageModel'),
        ),
    ]
