# Generated by Django 2.0.6 on 2018-06-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0005_auto_20180608_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_file',
            field=models.ImageField(upload_to=models.FilePathField(path='.')),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_path',
            field=models.FilePathField(path='.'),
        ),
    ]
