# Generated by Django 2.0.6 on 2018-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0006_auto_20180608_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_images',
            field=models.ManyToManyField(related_name='event_image_list', to='map_site.ImageModel'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_file',
            field=models.ImageField(upload_to='map_site.static.images'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_images',
            field=models.ManyToManyField(related_name='place_image_list', to='map_site.ImageModel'),
        ),
    ]
