# Generated by Django 2.0.6 on 2018-06-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_site', '0007_auto_20180608_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_file',
            field=models.ImageField(upload_to='map_site/static/images/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
